require "user.settings"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.dashboard"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.indent-guide"
require "user.toggleterm"

