[window]
padding = { x = 8, y = 8 }
opacity = 0.95

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 11.0

[colors.primary]
background = '#0f1419'
foreground = '#bfbdb6'

[colors.normal]
black   = '#000000'
red     = '#ff3333'
green   = '#b8cc52'
yellow  = '#e7c547'
blue    = '#36a3d9'
magenta = '#f07178'
cyan    = '#95e6cb'
white   = '#ffffff'

# [colors.bright]
# black = "#686868"
# blue = "#59C2FF"
# cyan = "#95E6CB"
# green = "#C2D94C"
# magenta = "#FFEE99"
# red = "#F07178"
# white = "#FFFFFF"
# yellow = "#FFB454"
#
# [colors.normal]
# black = "#01060E"
# blue = "#53BDFA"
# cyan = "#90E1C6"
# green = "#91B362"
# magenta = "#FAE994"
# red = "#EA6C73"
# white = "#C7C7C7"
# yellow = "#F9AF4F"
#
# [colors.primary]
# background = "#0A0E14"
# foreground = "#B3B1AD"
#
# [font]
# size = 11
#
# [font.bold]
# family = "Fira Code Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "Fira Code Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "Fira Code Nerd Font"
# style = "Italic"
#
# [font.normal]
# family = "Fira Code Nerd Font"
# style = "Regular"
#
# [window]
# opacity = 1.0
#
# [window.padding]
# x = 2
# y = 2
